POST http://localhost:3002/register/
Contents-Type: application/json

{
  "userInfo": {
    "username": "turbo",
    "password": "testi",
    "email": "testi1213@testi.com",
    "name": "Testi",
    "lastname": "Käyttäjä"
  }
}